# Requires a .env-File, see example.env
version: '3'
services:
  frontend:
    build:
      context: ${FRONTEND_PATH}
    ports:
      - "8000:80"
    links:
      - backend:backend
    networks:
      - lang

  backend:
    build: ${BACKEND_PATH}
    ports:
      - "8080:5000"
    environment:
      PORT: 5000
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      DB_HOST: db
      DB_USERNAME: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    links:
      - db:db
    networks:
      - lang

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

    networks:
      - lang


networks:
  lang:
